//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationFramework.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValidationFramework.Localization.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be between {0} and {1}..
        /// </summary>
        internal static string CannotBeBetween {
            get {
                return ResourceManager.GetString("CannotBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        internal static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be equal to {0}..
        /// </summary>
        internal static string CannotBeEqualTo {
            get {
                return ResourceManager.GetString("CannotBeEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be greater than {0}..
        /// </summary>
        internal static string CannotBeGreaterThan {
            get {
                return ResourceManager.GetString("CannotBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be greater than or equal to {0}..
        /// </summary>
        internal static string CannotBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("CannotBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be less than {0}..
        /// </summary>
        internal static string CannotBeLessThan {
            get {
                return ResourceManager.GetString("CannotBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be less than or equal to {0}..
        /// </summary>
        internal static string CannotBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("CannotBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot have more than or equal to {0} items..
        /// </summary>
        internal static string CannotBeLongerThan {
            get {
                return ResourceManager.GetString("CannotBeLongerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or white space..
        /// </summary>
        internal static string CannotBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("CannotBeNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be one of: {0}..
        /// </summary>
        internal static string CannotBeOneOf {
            get {
                return ResourceManager.GetString("CannotBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot have less than or equal to {0} items..
        /// </summary>
        internal static string CannotBeShorterThan {
            get {
                return ResourceManager.GetString("CannotBeShorterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be sub-type of {0}..
        /// </summary>
        internal static string CannotBeSubTypeOf {
            get {
                return ResourceManager.GetString("CannotBeSubTypeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be type of {0}..
        /// </summary>
        internal static string CannotBeTypeOf {
            get {
                return ResourceManager.GetString("CannotBeTypeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot contain duplicates..
        /// </summary>
        internal static string CannotContainDuplicates {
            get {
                return ResourceManager.GetString("CannotContainDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot contain null..
        /// </summary>
        internal static string CannotContainNull {
            get {
                return ResourceManager.GetString("CannotContainNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot match {0}..
        /// </summary>
        internal static string CannotMatch {
            get {
                return ResourceManager.GetString("CannotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a date..
        /// </summary>
        internal static string MustBeADate {
            get {
                return ResourceManager.GetString("MustBeADate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1}..
        /// </summary>
        internal static string MustBeBetween {
            get {
                return ResourceManager.GetString("MustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be empty..
        /// </summary>
        internal static string MustBeEmpty {
            get {
                return ResourceManager.GetString("MustBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be equal to {0}..
        /// </summary>
        internal static string MustBeEqualTo {
            get {
                return ResourceManager.GetString("MustBeEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than {0}..
        /// </summary>
        internal static string MustBeGreaterThan {
            get {
                return ResourceManager.GetString("MustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than or equal to {0}..
        /// </summary>
        internal static string MustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("MustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be in the future..
        /// </summary>
        internal static string MustBeInTheFuture {
            get {
                return ResourceManager.GetString("MustBeInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be in the past..
        /// </summary>
        internal static string MustBeInThePast {
            get {
                return ResourceManager.GetString("MustBeInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than {0}..
        /// </summary>
        internal static string MustBeLessThan {
            get {
                return ResourceManager.GetString("MustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than or equal to {0}..
        /// </summary>
        internal static string MustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("MustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be lower case..
        /// </summary>
        internal static string MustBeLowerCase {
            get {
                return ResourceManager.GetString("MustBeLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be null..
        /// </summary>
        internal static string MustBeNull {
            get {
                return ResourceManager.GetString("MustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be null or empty..
        /// </summary>
        internal static string MustBeNullOrEmpty {
            get {
                return ResourceManager.GetString("MustBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be one of: {0}..
        /// </summary>
        internal static string MustBeOneOf {
            get {
                return ResourceManager.GetString("MustBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be precise to {0} decimal places..
        /// </summary>
        internal static string MustBePreciseToDecimalPlaces {
            get {
                return ResourceManager.GetString("MustBePreciseToDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be title case..
        /// </summary>
        internal static string MustBeTitleCase {
            get {
                return ResourceManager.GetString("MustBeTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be today..
        /// </summary>
        internal static string MustBeToday {
            get {
                return ResourceManager.GetString("MustBeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be type of {0}..
        /// </summary>
        internal static string MustBeTypeOf {
            get {
                return ResourceManager.GetString("MustBeTypeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be upper case..
        /// </summary>
        internal static string MustBeUpperCase {
            get {
                return ResourceManager.GetString("MustBeUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid date..
        /// </summary>
        internal static string MustBeValidDate {
            get {
                return ResourceManager.GetString("MustBeValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid directory path..
        /// </summary>
        internal static string MustBeValidDirectoryPath {
            get {
                return ResourceManager.GetString("MustBeValidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid file name..
        /// </summary>
        internal static string MustBeValidFileName {
            get {
                return ResourceManager.GetString("MustBeValidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid file path..
        /// </summary>
        internal static string MustBeValidFilePath {
            get {
                return ResourceManager.GetString("MustBeValidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid time span..
        /// </summary>
        internal static string MustBeValidTimeSpan {
            get {
                return ResourceManager.GetString("MustBeValidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid URI..
        /// </summary>
        internal static string MustBeValidUri {
            get {
                return ResourceManager.GetString("MustBeValidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must contain duplicates..
        /// </summary>
        internal static string MustContainDuplicates {
            get {
                return ResourceManager.GetString("MustContainDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must contain null..
        /// </summary>
        internal static string MustContainNull {
            get {
                return ResourceManager.GetString("MustContainNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must match {0}..
        /// </summary>
        internal static string MustMatch {
            get {
                return ResourceManager.GetString("MustMatch", resourceCulture);
            }
        }
    }
}
